services:
  entelechy:
    build:
      #context defines either a path to a directory containing a Dockerfile
      #, or a URL to a git repository.
      # If not set explicitly, context defaults to project directory (.).
      context: ./ 
      target: build 
    # volumes:
    # - data:/data
      
  #web:
  #  image: nginx
  #  volumes:
  #    - data:/data
  #    - type: bind
  #      source: ./nginx.conf
  #      target: /etc/nginx/nginx.conf
  #    
  #  ports:
  #    - 80:80
  web:
    build:
      context: ./
      target: production
  # volumes:
      #- data:/data
    ports:
      - 80:80
    develop:
      watch:
        - action: sync
          path: ./data
          target: /data
        #volumes:
  #data:






