services:
  entelechy:
    image: nginx
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      # host:container ports
      - "3000:80"
    environment:
      - NGINX_PORT=80
volumes:
  store:
